services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis: 
    image: redis:7-alpine
    platform: linux/amd64
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "8000:8000"
    environment:
      APP_ENV: development
      DEBUG: "true"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      COGNITO_REGION: ${COGNITO_REGION}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ./backend:/app
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_AI_URL: http://localhost:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  ai:
    build:
      context: ./ai
      target: development
    ports:
      - "8001:8001"
    environment:
      OPENCV_FFMPEG_CAPTURE_OPTIONS: "rtsp_transport;tcp"
      BACKEND_URL: http://backend:8000
    volumes:
      - ./ai:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload

volumes:
  postgres_data:
  redis_data:
  frontend_node_modules: