services:
  # redis:
  #   image: redis:7-alpine
  #   container_name: redis_cache
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s

  backend:
    build:
      context: ./backend
      target: production
    environment:
      APP_ENV: production
      DEBUG: "false"
      TESTING: "false"
      DATABASE_URL: ${DATABASE_URL}
      # REDIS_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      COGNITO_REGION: ${COGNITO_REGION}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      FRONTEND_URL: ${FRONTEND_URL}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_WHATSAPP_FROM: ${TWILIO_WHATSAPP_FROM}
      NOTIFICATION_ENABLED: ${NOTIFICATION_ENABLED}
      SMTP_SENDER_EMAIL: ${SMTP_SENDER_EMAIL}
      SMTP_APP_PASSWORD: ${SMTP_APP_PASSWORD}
      RTSP_ENCRYPTION_KEY: ${RTSP_ENCRYPTION_KEY}
      MEDIAMTX_PUBLISH_MASTER_KEY: ${MEDIAMTX_PUBLISH_MASTER_KEY}
      INTERNAL_API_TOKEN: ${INTERNAL_API_TOKEN}
    restart: always
    # volumes:
    #   - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      # redis:
      #   condition: service_healthy

  # ai:
  #   build:
  #     context: ./ai
  #     target: development
  #   platform: linux/amd64
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     OPENCV_FFMPEG_CAPTURE_OPTIONS: "rtsp_transport;tcp"
  #     BACKEND_URL: http://backend:8000
  #   volumes:
  #     - ./ai:/app
  #   command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload

  mediamtx:
    environment:
      MTX_WEBRTCENCRYPTION: "yes"
      MTX_WEBRTCSERVERCERT: /certs/fullchain.pem
      MTX_WEBRTCSERVERKEY: /certs/privkey.pem
      MTX_WEBRTCADDITIONALHOSTS: ${MTX_WEBRTCADDITIONALHOSTS}
      MTX_WEBRTCALLOWORIGIN: ${MTX_WEBRTCALLOWORIGIN}
      MTX_AUTHHTTPADDRESS: ${MTX_AUTHHTTPADDRESS}
    build:
      context: ./mediamtx
    ports:
      - "8554:8554" # RTSP
      - "8889:8889" # WebRTC
      - "8189:8189/udp"
      - "9997:9997" # API
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx/mediamtx.yml
      - /opt/mediamtx-certs:/certs:ro
    restart: always

volumes:
  # redis_data:
