services:
  # redis: 
  #   image: redis:7-alpine
  #   container_name: redis_cache
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s

  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      DEBUG: "false"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      # REDIS_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      COGNITO_REGION: ${COGNITO_REGION}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      FRONTEND_URL: ${FRONTEND_URL}
    restart: always
    # volumes:
    #   - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      # redis:
      #   condition: service_healthy

  # ai:
  #   build:
  #     context: ./ai
  #     target: development
  #   platform: linux/amd64
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     OPENCV_FFMPEG_CAPTURE_OPTIONS: "rtsp_transport;tcp"
  #     BACKEND_URL: http://backend:8000
  #   volumes:
  #     - ./ai:/app
  #   command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload

  mediamtx:
    build:
      context: ./mediamtx
    platform: linux/amd64
    ports:
      - "8554:8554"    # RTSP
      - "8889:8889"    # WebRTC
      - "9997:9997"    # API
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx/mediamtx.yml
    restart: always

volumes:
  # redis_data: