"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Loader2 } from "lucide-react";

import {
    AlertCard,
    type Alert,
} from "@/components/shared/AlertCard";
import { fetchPropertyAlerts } from "@/lib/api/alert";

export default function PropertyAlertsPage() {
    const { propertyId } = useParams<{
        propertyId: string;
    }>();

    const [alerts, setAlerts] = useState<Alert[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const controller = new AbortController();

        fetchPropertyAlerts(
            propertyId,
            undefined,
            controller.signal,
        )
            .then((result) => {
                setAlerts(result.alerts);
            })
            .catch((error: unknown) => {
                if (
                    error instanceof DOMException &&
                    error.name === "AbortError"
                ) {
                    return;
                }

                console.error(
                    "Failed to load property alerts:",
                    error,
                );
            })
            .finally(() => {
                if (!controller.signal.aborted) {
                    setLoading(false);
                }
            });

        return () => {
            controller.abort();
        };
    }, [propertyId]);

    return (
        <main className="min-h-full bg-black px-6 py-8 text-white md:px-8">
            <div className="mx-auto w-full max-w-6xl">
                <header className="border-b border-white/10 pb-6">
                    <p className="text-sm text-emerald-400">
                        My home
                    </p>

                    <h1 className="mt-2 text-2xl font-semibold tracking-tight">
                        Property alerts
                    </h1>

                    <p className="mt-2 text-sm leading-relaxed text-white/50">
                        Alerts generated by cameras connected to this
                        property.
                    </p>
                </header>

                <section
                    aria-label="Property alerts"
                    aria-live="polite"
                    className="pt-7"
                >
                    {loading ? (
                        <div className="flex items-center justify-center py-20">
                            <Loader2 className="size-5 animate-spin text-emerald-400" />
                        </div>
                    ) : (
                        <div className="space-y-3">
                            {alerts.map((alert) => (
                                <AlertCard
                                    key={alert.id}
                                    alert={alert}
                                    broadcasting={false}
                                />
                            ))}
                        </div>
                    )}
                </section>
            </div>
        </main>
    );
}
