"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import {
    AlertCircle,
    Loader2,
    RefreshCw,
} from "lucide-react";

import {
    AlertCard,
    getSeverity,
    type Alert,
} from "@/components/shared/AlertCard";
import { Button } from "@/components/ui/button";
import {
    acknowledgeAlert,
    fetchPropertyAlerts,
} from "@/lib/api/alert";
import { useUserContext } from "@/hooks/use-user-context";

export default function PropertyAlertsPage() {
    const { propertyId } = useParams<{
        propertyId: string;
    }>();

    const { data: userContext } = useUserContext();

    const isPropertyAdmin = Boolean(
        userContext?.properties.some(
            (property) =>
                property.id === propertyId &&
                property.is_admin,
        ),
    );

    const [alerts, setAlerts] = useState<Alert[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [actionError, setActionError] = useState<string | null>(
        null,
    );
    const [refreshKey, setRefreshKey] = useState(0);

    useEffect(() => {
        const controller = new AbortController();


        fetchPropertyAlerts(
            propertyId,
            undefined,
            controller.signal,
        )
            .then((result) => {
                if (controller.signal.aborted) {
                    return;
                }

                setAlerts(result.alerts);
            })
            .catch((requestError: unknown) => {
                if (
                    requestError instanceof DOMException &&
                    requestError.name === "AbortError"
                ) {
                    return;
                }

                setError(
                    requestError instanceof Error
                        ? requestError.message
                        : "Failed to load property alerts.",
                );
            })
            .finally(() => {
                if (!controller.signal.aborted) {
                    setLoading(false);
                }
            });

        return () => {
            controller.abort();
        };
    }, [propertyId, refreshKey]);

    async function handleAcknowledge(alertId: string) {
        const alert = alerts.find(
            (currentAlert) => currentAlert.id === alertId,
        );

        if (!alert || !isPropertyAdmin) {
            return;
        }

        if (getSeverity(alert.detection_type) === "CRITICAL") {
            return;
        }

        setActionError(null);

        try {
            await acknowledgeAlert(alertId);

            setAlerts((currentAlerts) =>
                currentAlerts.map((currentAlert) =>
                    currentAlert.id === alertId
                        ? {
                              ...currentAlert,
                              status: "ACKNOWLEDGED",
                          }
                        : currentAlert,
                ),
            );
        } catch (requestError: unknown) {
            setActionError(
                requestError instanceof Error
                    ? requestError.message
                    : "Failed to acknowledge alert.",
            );
        }
    }

    return (
        <main className="min-h-full bg-brand-void px-6 py-8 text-brand-frost md:px-8">
            <div className="mx-auto w-full max-w-6xl">
                <header className="border-b border-border pb-6">
                    <div className="flex items-center justify-between gap-4">
                        <div>
                            <p className="text-sm text-brand-green">
                                My home
                            </p>

                            <h1 className="mt-2 text-2xl font-semibold tracking-tight">
                                Property alerts
                            </h1>

                            <p className="mt-2 text-sm leading-relaxed text-brand-ash">
                                Alerts generated by cameras connected to this
                                property.
                            </p>
                        </div>

                        <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() =>
                                setRefreshKey(
                                    (current) => current + 1,
                                )
                            }
                            disabled={loading}
                            className="text-brand-green hover:bg-brand-slate hover:text-brand-frost"
                        >
                            <RefreshCw
                                className={`mr-1.5 size-3.5 ${
                                    loading ? "animate-spin" : ""
                                }`}
                            />
                            Refresh
                        </Button>
                    </div>
                </header>

                <section
                    aria-label="Property alerts"
                    aria-live="polite"
                    className="pt-7"
                >
                    {actionError && (
                        <div
                            role="alert"
                            className="mb-4 flex items-start gap-3 border border-brand-threat/25 bg-brand-threat/10 px-4 py-3 text-sm text-brand-threat"
                        >
                            <AlertCircle className="mt-0.5 size-4 shrink-0 text-brand-threat" />

                            <p>{actionError}</p>
                        </div>
                    )}

                    {loading ? (
                        <div className="flex items-center justify-center py-20">
                            <Loader2 className="size-5 animate-spin text-brand-green" />
                        </div>
                    ) : error ? (
                        <div
                            role="alert"
                            className="flex items-start gap-3 border border-brand-threat/25 bg-brand-threat/10 px-4 py-3 text-sm text-brand-threat"
                        >
                            <AlertCircle className="mt-0.5 size-4 shrink-0 text-brand-threat" />

                            <div>
                                <p>{error}</p>

                                <button
                                    type="button"
                                    onClick={() =>
                                        setRefreshKey(
                                            (current) => current + 1,
                                        )
                                    }
                                    className="mt-2 text-xs text-brand-threat underline underline-offset-4 hover:text-brand-threat"
                                >
                                    Try again
                                </button>
                            </div>
                        </div>
                    ) : alerts.length === 0 ? (
                        <div className="border-t border-border py-16 text-center">
                            <p className="text-sm font-medium text-brand-ash">
                                No alerts for this property
                            </p>

                            <p className="mt-2 text-sm text-brand-ash/70">
                                Alerts from cameras on this property will
                                appear here.
                            </p>
                        </div>
                    ) : (
                        <div className="space-y-3">
                            {alerts.map((alert) => (
                                <AlertCard
                                    key={alert.id}
                                    alert={alert}
                                    onAcknowledge={
                                        isPropertyAdmin &&
                                        getSeverity(
                                            alert.detection_type,
                                        ) !== "CRITICAL"
                                            ? handleAcknowledge
                                            : undefined
                                    }
                                    broadcasting={false}
                                />
                            ))}
                        </div>
                    )}
                </section>
            </div>
        </main>
    );
}
