"""Removed IP address from audit_log table

Revision ID: 04e1a8f78767
Revises: e184724b7ff8
Create Date: 2026-07-04 12:38:23.988058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04e1a8f78767'
down_revision: Union[str, Sequence[str], None] = 'e184724b7ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
