"""add index on alert.status

Revision ID: 05696974518c
Revises: 3edaed50faf0
Create Date: 2026-09-28 19:13:14.422527

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '05696974518c'
down_revision: Union[str, Sequence[str], None] = '3edaed50faf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alert_status'), 'alert', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_status'), table_name='alert')
    # ### end Alembic commands ###
