"""add clip metadata to tracking sightings

Revision ID: 06dddc13595a
Revises: 549c343e8433
Create Date: 2026-09-24 08:43:04.213398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dddc13595a'
down_revision: Union[str, Sequence[str], None] = '549c343e8433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_sighting', sa.Column('clip_s3_key', sa.String(length=512), nullable=True))
    op.add_column('tracking_sighting', sa.Column('clip_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_sighting', 'clip_expires_at')
    op.drop_column('tracking_sighting', 'clip_s3_key')
    # ### end Alembic commands ###
