"""Updated target entity enum with security officer

Revision ID: 0ca09c23ed0c
Revises: 548f8f4f39f0
Create Date: 2026-09-15 22:44:40.032503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0ca09c23ed0c'
down_revision: Union[str, Sequence[str], None] = '548f8f4f39f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE targetentity "
        "ADD VALUE IF NOT EXISTS 'SECURITYOFFICER'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
