"""add clip columns to detection_event

Revision ID: 1c4ab71bc39e
Revises: ed7933c51c73
Create Date: 2026-07-11 06:19:16.709837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1c4ab71bc39e'
down_revision: Union[str, Sequence[str], None] = 'ed7933c51c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'enabled')
    op.drop_column('camera', 'name')
    op.add_column('detection_event', sa.Column('clip_s3_key', sa.String(), nullable=True))
    op.add_column('detection_event', sa.Column('clip_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_event', 'clip_expires_at')
    op.drop_column('detection_event', 'clip_s3_key')
    op.add_column('camera', sa.Column('name', sa.VARCHAR(), server_default=sa.text("'Camera'::character varying"), autoincrement=False, nullable=False))
    op.add_column('camera', sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
