"""restore camera name and enabled columns

Revision ID: 2405a75eb269
Revises: 1c4ab71bc39e
Create Date: 2026-07-11 06:59:11.300458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2405a75eb269'
down_revision: Union[str, Sequence[str], None] = '1c4ab71bc39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('name', sa.String(), server_default='Camera', nullable=False))
    op.add_column('camera', sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'enabled')
    op.drop_column('camera', 'name')
    # ### end Alembic commands ###
