"""Changed Audit Log Table

Revision ID: 24ebe8a57883
Revises: 919661e27f6e
Create Date: 2026-07-04 15:13:19.174956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24ebe8a57883'
down_revision: Union[str, Sequence[str], None] = 'c6da553e3309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_log', sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('audit_log', 'metadata')
    op.drop_column('audit_log', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=False))
    op.add_column('audit_log', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audit_log', 'new_values')
    op.drop_column('audit_log', 'old_values')
    # ### end Alembic commands ###
