"""Added edge agent credential and pairing tokens tables

Revision ID: 47ad52d07437
Revises: 398c3426728f
Create Date: 2026-07-24 07:42:54.874234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ad52d07437'
down_revision: Union[str, Sequence[str], None] = '398c3426728f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge_agents_credentials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_agents_credentials_key_hash'), 'edge_agents_credentials', ['key_hash'], unique=True)
    op.create_table('pairing_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now() + interval '10 minutes'"), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairing_tokens_token'), 'pairing_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pairing_tokens_token'), table_name='pairing_tokens')
    op.drop_table('pairing_tokens')
    op.drop_index(op.f('ix_edge_agents_credentials_key_hash'), table_name='edge_agents_credentials')
    op.drop_table('edge_agents_credentials')
    # ### end Alembic commands ###
