"""Added location attributes to security officer table

Revision ID: 548f8f4f39f0
Revises: ad46ced5f06b
Create Date: 2026-09-15 10:36:19.021335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '548f8f4f39f0'
down_revision: Union[str, Sequence[str], None] = 'ad46ced5f06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_officer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neighbourhood_user_id', sa.UUID(), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'BUSY', 'UNAVAILABLE', name='availability_status'), nullable=True),
    sa.Column('last_known_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['neighbourhood_user_id'], ['neighbourhood_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neighbourhood_user_id')
    )
    #op.create_index('idx_security_officer_last_known_location', 'security_officer', ['last_known_location'], unique=False, postgresql_using='gist')
    op.create_index('ix_security_officer_lookup', 'security_officer', ['neighbourhood_user_id', 'availability_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_officer_lookup', table_name='security_officer')
    #op.drop_index('idx_security_officer_last_known_location', table_name='security_officer', postgresql_using='gist')
    op.drop_table('security_officer')
    # ### end Alembic commands ###
