"""Added location attributes to security officer table

Revision ID: 548f8f4f39f0
Revises: ad46ced5f06b
Create Date: 2026-09-15 10:36:19.021335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '548f8f4f39f0'
down_revision: Union[str, Sequence[str], None] = 'a57ec0c60e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_officer', sa.Column('last_known_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),)
    op.add_column('security_officer', sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),)
    
    #op.create_index('idx_security_officer_last_known_location', 'security_officer', ['last_known_location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('idx_security_officer_last_known_location', table_name='security_officer')
    op.drop_column('security_officer', 'location_updated_at')
    op.drop_column('security_officer', 'last_known_location')
    # ### end Alembic commands ###
