"""Added edge agent credential and pairing tokens tables

Revision ID: 58adda1ff3fb
Revises: 398c3426728f
Create Date: 2026-07-23 15:29:05.373046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '58adda1ff3fb'
down_revision: Union[str, Sequence[str], None] = '398c3426728f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
