"""Added Push Device Table

Revision ID: 649bafafac38
Revises: a0e51455c92c
Create Date: 2026-09-23 09:47:05.595357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '649bafafac38'
down_revision: Union[str, Sequence[str], None] = 'a0e51455c92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_device',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_index(op.f('ix_push_device_user_id'), 'push_device', ['user_id'], unique=False)
    op.drop_index(op.f('ix_tracking_subject_reference_embedding_hnsw'), table_name='tracking_subject', postgresql_ops={'reference_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tracking_subject_reference_embedding_hnsw'), 'tracking_subject', ['reference_embedding'], unique=False, postgresql_ops={'reference_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_push_device_user_id'), table_name='push_device')
    op.drop_table('push_device')
    # ### end Alembic commands ###
