"""Added enums to notification table and made alert_id nullable

Revision ID: 6e47defa1510
Revises: 8940966428e1
Create Date: 2026-09-25 10:12:41.150993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e47defa1510'
down_revision: Union[str, Sequence[str], None] = '8940966428e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alert_acknowledged_by_fkey'), 'alert', type_='foreignkey')
    op.drop_constraint(op.f('alert_confirmed_by_fkey'), 'alert', type_='foreignkey')
    op.create_foreign_key(None, 'alert', 'users', ['confirmed_by'], ['id'])
    op.create_foreign_key(None, 'alert', 'users', ['acknowledged_by'], ['id'])
    op.alter_column('notification', 'alert_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('tracking_sighting', 'clip_s3_key')
    op.drop_column('tracking_sighting', 'clip_expires_at')
    op.execute("ALTER TYPE notification_channel ADD VALUE IF NOT EXISTS 'PUSH'")
    op.execute("ALTER TYPE notification_channel ADD VALUE IF NOT EXISTS 'WEBSOCKET'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_sighting', sa.Column('clip_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tracking_sighting', sa.Column('clip_s3_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.alter_column('notification', 'alert_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.create_foreign_key(op.f('alert_confirmed_by_fkey'), 'alert', 'users', ['confirmed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('alert_acknowledged_by_fkey'), 'alert', 'users', ['acknowledged_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
