"""add daily incident density aggregates

Revision ID: 7532e7c9f37e
Revises: 0b498cd245b5
Create Date: 2026-09-23 07:17:47.681999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7532e7c9f37e'
down_revision: Union[str, Sequence[str], None] = '0b498cd245b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_incident_density',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=False),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('cell_size_metres', sa.SmallInteger(), server_default='100', nullable=False),
    sa.Column('grid_x', sa.BigInteger(), nullable=False),
    sa.Column('grid_y', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('incident_count > 0', name='ck_daily_incident_density_positive_count'),
    sa.ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neighbourhood_id', 'incident_date', 'cell_size_metres', 'grid_x', 'grid_y', name='uq_daily_incident_density_cell')
    )
    op.create_index('ix_daily_incident_density_lookup', 'daily_incident_density', ['neighbourhood_id', 'incident_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_incident_density_lookup', table_name='daily_incident_density')
    op.drop_table('daily_incident_density')
    # ### end Alembic commands ###
