"""add cached danger zone cells

Revision ID: 81d08417eb88
Revises: 9bc903d75aba
Create Date: 2026-09-25 15:51:01.840159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '81d08417eb88'
down_revision: Union[str, Sequence[str], None] = '9bc903d75aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danger_zone_cell',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('cell_size_metres', sa.SmallInteger(), server_default='100', nullable=False),
    sa.Column('grid_x', sa.BigInteger(), nullable=False),
    sa.Column('grid_y', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('incident_score', sa.Float(), nullable=False),
    sa.Column('coverage_ratio', sa.Float(), nullable=False),
    sa.Column('coverage_sparsity', sa.Float(), nullable=False),
    sa.Column('danger_score', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('coverage_ratio BETWEEN 0 AND 1', name='ck_danger_zone_coverage_ratio'),
    sa.CheckConstraint('coverage_sparsity BETWEEN 0 AND 1', name='ck_danger_zone_coverage_sparsity'),
    sa.CheckConstraint('danger_score BETWEEN 0 AND 1', name='ck_danger_zone_danger_score'),
    sa.CheckConstraint('incident_count >= 0', name='ck_danger_zone_incident_count'),
    sa.CheckConstraint('incident_score BETWEEN 0 AND 1', name='ck_danger_zone_incident_score'),
    sa.CheckConstraint('window_start <= window_end', name='ck_danger_zone_valid_window'),
    sa.ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neighbourhood_id', 'window_end', 'grid_x', 'grid_y', name='uq_danger_zone_cell_snapshot')
    )
    op.create_index('ix_danger_zone_neighbourhood_window', 'danger_zone_cell', ['neighbourhood_id', 'window_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_danger_zone_neighbourhood_window', table_name='danger_zone_cell')
    op.drop_table('danger_zone_cell')
    # ### end Alembic commands ###
