"""Added neighbourhood_user table, and fixed other tables

Revision ID: 8b72bc8de0d6
Revises: b21f39d5eeeb
Create Date: 2026-08-06 21:12:15.327995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b72bc8de0d6'
down_revision: Union[str, Sequence[str], None] = 'b21f39d5eeeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighbourhood_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('RESIDENT', 'NEIGHBOURHOOD_ADMIN', 'SECURITY_OFFICER', name='neighbourhood_role'), nullable=False),
    sa.ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_neighbourhood_user_neighbourhood_role', 'neighbourhood_user', ['neighbourhood_id', 'role'], unique=False)
    op.create_index('ix_neighbourhood_user_user_lookup', 'neighbourhood_user', ['user_id'], unique=False)
    op.create_index('uq_neighbourhood_user_unique', 'neighbourhood_user', ['user_id', 'neighbourhood_id'], unique=True)
    op.create_table('edge_agent_credential',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_agent_credential_key_hash'), 'edge_agent_credential', ['key_hash'], unique=True)
    op.create_index('ix_edge_agent_credentials_property_id', 'edge_agent_credential', ['property_id'], unique=False)
    op.add_column('alert', sa.Column('frame_timestamp', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('alert', sa.Column('detection_type', sa.Enum('HUMAN_PRESENCE', 'LOITERING', 'PERIMETER_SCAN', 'WEAPON_DETECTED', 'FALL_DETECTED', name='detection_type'), nullable=False))
    op.add_column('alert', sa.Column('confidence_score', sa.Float(), nullable=False))
    op.add_column('alert', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('alert', sa.Column('processed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('alert', sa.Column('clip_s3_key', sa.String(), nullable=True))
    op.add_column('alert', sa.Column('clip_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_alert_resolved_by'), 'alert', ['resolved_by'], unique=False)
    op.create_index('ix_detection_event_camera_timestamp', 'alert', ['camera_id', 'frame_timestamp'], unique=False)
    op.drop_constraint(op.f('alert_detection_event_id_fkey'), 'alert', type_='foreignkey')
    op.drop_column('alert', 'detection_event_id')
    target_entity_enum = postgresql.ENUM(
        "ALERT",
        "CAMERADETECTIONZONE",
        "CAMERA",
        "EDGEAGENTCREDENTIALS",
        "NEIGHBOURHOODJOINREQUEST",
        "NEIGHBOURHOOD",
        "NOTIFICATION",
        "PAIRINGTOKEN",
        "PROPERTYUSER",
        "PROPERTY",
        "RETENTIONPOLICY",
        "RISKSCOREHISTORY",
        "RISKTHRESHOLDCONFIG",
        "USER",
        "ZONE",
        name="targetentity",
    )

    # PostgreSQL enum types must exist before a TEXT column can use them.
    target_entity_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "audit_log",
        "target_entity_type",
        existing_type=sa.TEXT(),
        type_=target_entity_enum,
        existing_nullable=True,
        postgresql_using="target_entity_type::text::targetentity",
    )
    op.create_index('ix_audit_log_entity', 'audit_log', ['target_entity_type', 'target_entity_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_log_user_action_timestamp', 'audit_log', ['user_id', 'action', 'timestamp'], unique=False)
    op.create_index('ix_audit_log_user_timestamp', 'audit_log', ['user_id', 'timestamp'], unique=False)
    op.create_index('ix_camera_property_visibility', 'camera', ['property_id', 'visibility'], unique=False)
    op.drop_constraint(op.f('camera_neighbourhood_id_fkey'), 'camera', type_='foreignkey')
    op.drop_column('camera', 'neighbourhood_id')
    op.create_index(op.f('ix_camera_detection_zone_camera_id'), 'camera_detection_zone', ['camera_id'], unique=False)
    op.create_index(op.f('ix_geospatial_zone_neighbourhood_id'), 'geospatial_zone', ['neighbourhood_id'], unique=False)
    op.alter_column('neighbourhood_join_request', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='join_request_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_index('ix_join_request_neighbourhood_created_at', 'neighbourhood_join_request', ['neighbourhood_id', 'created_at'], unique=False)
    op.create_index('ix_join_request_neighbourhood_status', 'neighbourhood_join_request', ['neighbourhood_id', 'status'], unique=False)
    op.create_index('ix_join_request_user_id', 'neighbourhood_join_request', ['user_id'], unique=False)
    op.alter_column('notification', 'channel',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('WHATSAPP', 'EMAIL', name='notification_channel'),
               existing_nullable=False)
    op.alter_column('notification', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SENT', 'FAILED', name='notification_status'),
               existing_nullable=False)
    op.create_index('ix_notification_alert_id', 'notification', ['alert_id'], unique=False)
    op.create_index('ix_notification_user_sent_at', 'notification', ['user_id', 'sent_at'], unique=False)
    op.drop_constraint(op.f('notification_alert_id_fkey'), 'notification', type_='foreignkey')
    op.drop_constraint(op.f('notification_user_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'alert', ['alert_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notification', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pairing_tokens', 'property_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('pairing_tokens_property_id_fkey'), 'pairing_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'pairing_tokens', 'property', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_property_neighbourhood_id'), 'property', ['neighbourhood_id'], unique=False)
    op.drop_constraint(op.f('property_neighbourhood_id_fkey'), 'property', type_='foreignkey')
    op.create_foreign_key(None, 'property', 'neighbourhood', ['neighbourhood_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_property_user_property_id'), 'property_user', ['property_id'], unique=False)
    op.drop_constraint(op.f('property_user_property_id_fkey'), 'property_user', type_='foreignkey')
    op.drop_constraint(op.f('property_user_user_id_fkey'), 'property_user', type_='foreignkey')
    op.create_foreign_key(None, 'property_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'property_user', 'property', ['property_id'], ['id'], ondelete='CASCADE')
    op.alter_column('retention_policy', 'camera_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'retention_policy', ['camera_id'])
    op.drop_constraint(op.f('retention_policy_neighbourhood_id_fkey'), 'retention_policy', type_='foreignkey')
    op.drop_constraint(op.f('retention_policy_camera_id_fkey'), 'retention_policy', type_='foreignkey')
    op.create_foreign_key(None, 'retention_policy', 'camera', ['camera_id'], ['id'], ondelete='CASCADE')
    op.drop_column('retention_policy', 'neighbourhood_id')
    op.create_index('ix_risk_score_history_neighbourhood_calculated_at', 'risk_score_history', ['neighbourhood_id', 'calculated_at'], unique=False)
    op.drop_constraint(op.f('risk_score_history_neighbourhood_id_fkey'), 'risk_score_history', type_='foreignkey')
    op.create_foreign_key(None, 'risk_score_history', 'neighbourhood', ['neighbourhood_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_risk_threshold_config_neighbourhood_id'), 'risk_threshold_config', ['neighbourhood_id'], unique=False)
    op.drop_constraint(op.f('risk_threshold_config_neighbourhood_id_fkey'), 'risk_threshold_config', type_='foreignkey')
    op.create_foreign_key(None, 'risk_threshold_config', 'neighbourhood', ['neighbourhood_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('system_role', sa.Enum('SYSTEM_ADMIN', 'RESIDENT', 'SECURITY_OFFICER', name='userrole'), nullable=False))
    op.drop_constraint(op.f('users_neighbourhood_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'neighbourhood_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('SYSTEM_ADMIN', 'RESIDENT', 'NEIGHBOURHOOD_ADMIN', 'PROPERTY_ADMIN', 'USER', 'SECURITY_OFFICER', name='userrole'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('neighbourhood_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_neighbourhood_id_fkey'), 'users', 'neighbourhood', ['neighbourhood_id'], ['id'])
    op.drop_column('users', 'system_role')
    op.drop_constraint(None, 'risk_threshold_config', type_='foreignkey')
    op.create_foreign_key(op.f('risk_threshold_config_neighbourhood_id_fkey'), 'risk_threshold_config', 'neighbourhood', ['neighbourhood_id'], ['id'])
    op.drop_index(op.f('ix_risk_threshold_config_neighbourhood_id'), table_name='risk_threshold_config')
    op.drop_constraint(None, 'risk_score_history', type_='foreignkey')
    op.create_foreign_key(op.f('risk_score_history_neighbourhood_id_fkey'), 'risk_score_history', 'neighbourhood', ['neighbourhood_id'], ['id'])
    op.drop_index('ix_risk_score_history_neighbourhood_calculated_at', table_name='risk_score_history')
    op.add_column('retention_policy', sa.Column('neighbourhood_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'retention_policy', type_='foreignkey')
    op.create_foreign_key(op.f('retention_policy_camera_id_fkey'), 'retention_policy', 'camera', ['camera_id'], ['id'])
    op.create_foreign_key(op.f('retention_policy_neighbourhood_id_fkey'), 'retention_policy', 'neighbourhood', ['neighbourhood_id'], ['id'])
    op.drop_constraint(None, 'retention_policy', type_='unique')
    op.alter_column('retention_policy', 'camera_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'property_user', type_='foreignkey')
    op.drop_constraint(None, 'property_user', type_='foreignkey')
    op.create_foreign_key(op.f('property_user_user_id_fkey'), 'property_user', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('property_user_property_id_fkey'), 'property_user', 'property', ['property_id'], ['id'])
    op.drop_index(op.f('ix_property_user_property_id'), table_name='property_user')
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.create_foreign_key(op.f('property_neighbourhood_id_fkey'), 'property', 'neighbourhood', ['neighbourhood_id'], ['id'])
    op.drop_index(op.f('ix_property_neighbourhood_id'), table_name='property')
    op.drop_constraint(None, 'pairing_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('pairing_tokens_property_id_fkey'), 'pairing_tokens', 'property', ['property_id'], ['id'])
    op.alter_column('pairing_tokens', 'property_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_user_id_fkey'), 'notification', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('notification_alert_id_fkey'), 'notification', 'alert', ['alert_id'], ['id'])
    op.drop_index('ix_notification_user_sent_at', table_name='notification')
    op.drop_index('ix_notification_alert_id', table_name='notification')
    op.alter_column('notification', 'status',
               existing_type=sa.Enum('SENT', 'FAILED', name='notification_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('notification', 'channel',
               existing_type=sa.Enum('WHATSAPP', 'EMAIL', name='notification_channel'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('ix_join_request_user_id', table_name='neighbourhood_join_request')
    op.drop_index('ix_join_request_neighbourhood_status', table_name='neighbourhood_join_request')
    op.drop_index('ix_join_request_neighbourhood_created_at', table_name='neighbourhood_join_request')
    op.alter_column('neighbourhood_join_request', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='join_request_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.drop_index(op.f('ix_geospatial_zone_neighbourhood_id'), table_name='geospatial_zone')
    op.drop_index(op.f('ix_camera_detection_zone_camera_id'), table_name='camera_detection_zone')
    op.add_column('camera', sa.Column('neighbourhood_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('camera_neighbourhood_id_fkey'), 'camera', 'neighbourhood', ['neighbourhood_id'], ['id'])
    op.drop_index('ix_camera_property_visibility', table_name='camera')
    op.drop_index('ix_audit_log_user_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_log_user_action_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.alter_column('audit_log', 'target_entity_type',
               existing_type=sa.Enum('ALERT', 'CAMERADETECTIONZONE', 'CAMERA', 'EDGEAGENTCREDENTIALS', 'NEIGHBOURHOODJOINREQUEST', 'NEIGHBOURHOOD', 'NOTIFICATION', 'PAIRINGTOKEN', 'PROPERTYUSER', 'PROPERTY', 'RETENTIONPOLICY', 'RISKSCOREHISTORY', 'RISKTHRESHOLDCONFIG', 'USER', 'ZONE', name='targetentity'),
               type_=sa.TEXT(),
               existing_nullable=True,
               postgresql_using="target_entity_type::text")
    op.add_column('alert', sa.Column('detection_event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('alert_detection_event_id_fkey'), 'alert', 'detection_event', ['detection_event_id'], ['id'])
    op.drop_index('ix_detection_event_camera_timestamp', table_name='alert')
    op.drop_index(op.f('ix_alert_resolved_by'), table_name='alert')
    op.drop_column('alert', 'clip_expires_at')
    op.drop_column('alert', 'clip_s3_key')
    op.drop_column('alert', 'processed')
    op.drop_column('alert', 'thumbnail_url')
    op.drop_column('alert', 'confidence_score')
    op.drop_column('alert', 'detection_type')
    op.drop_column('alert', 'frame_timestamp')
    op.drop_index('ix_edge_agent_credentials_property_id', table_name='edge_agent_credential')
    op.drop_index(op.f('ix_edge_agent_credential_key_hash'), table_name='edge_agent_credential')
    op.drop_table('edge_agent_credential')
    op.drop_index('uq_neighbourhood_user_unique', table_name='neighbourhood_user')
    op.drop_index('ix_neighbourhood_user_user_lookup', table_name='neighbourhood_user')
    op.drop_index('ix_neighbourhood_user_neighbourhood_role', table_name='neighbourhood_user')
    op.drop_table('neighbourhood_user')
    # ### end Alembic commands ###
