"""add camera detection zones and confidence threshold

Revision ID: 8b7703bb085b
Revises: 919661e27f6e
Create Date: 2026-07-02 08:36:10.417020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8b7703bb085b'
down_revision: Union[str, Sequence[str], None] = '919661e27f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('confidence_threshold', sa.Float(), server_default='0.5', nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('neighbourhood_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'neighbourhood', ['neighbourhood_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'neighbourhood_id')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('camera', 'confidence_threshold')
    # ### end Alembic commands ###
