"""Added security officer table with availability attribute

Revision ID: ad46ced5f06b
Revises: e8c4a2b1d6f0
Create Date: 2026-09-15 08:22:42.048246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ad46ced5f06b'
down_revision: Union[str, Sequence[str], None] = 'e8c4a2b1d6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edge_agent_credentials_property_last_seen'), table_name='edge_agent_credential')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_edge_agent_credentials_property_last_seen'), 'edge_agent_credential', ['property_id', 'last_seen_at'], unique=False)
    # ### end Alembic commands ###
