"""initial

Revision ID: c6da553e3309
Revises: 
Create Date: 2026-07-16 20:19:46.785119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6da553e3309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NOW = 'now()'
NEIGHBOURHOOD_ID = 'neighbourhood.id'
GEN_RANDOM_UUID = 'gen_random_uuid()'
USERS_ID = 'users.id'
PROPERTY_ID = 'property.id'
CAMERA_ID = 'camera.id'

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighbourhood',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('join_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text(NOW), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_table('geospatial_zone',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('polygon_boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('sensitivity_level', sa.Enum('LOW', 'HIGH', 'MEDIUM', 'CRITICAL', name='sensitivity_level'), server_default='MEDIUM', nullable=False),
    sa.ForeignKeyConstraint(['neighbourhood_id'], [NEIGHBOURHOOD_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_geospatial_zone_polygon_boundary', 'geospatial_zone', ['polygon_boundary'], unique=False, postgresql_using='gist')
    op.create_table('property',
    sa.Column('id', sa.UUID(), server_default=sa.text(GEN_RANDOM_UUID), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('property_type', sa.Enum('PRIVATE', 'PUBLIC', name='property_type'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text(NOW), nullable=False),
    sa.ForeignKeyConstraint(['neighbourhood_id'], [NEIGHBOURHOOD_ID], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('cognito_sub', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'RESIDENT', 'NEIGHBOURHOOD_ADMIN', 'PROPERTY_ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['neighbourhood_id'], [NEIGHBOURHOOD_ID], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_sub'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'REGISTER_CAMERA', 'DELETE_CAMERA', 'UPDTAE_ZONE_CONFIG', 'UPDTAE_THRESHOLD', 'ACKNOWLEDGE_ALERT', 'RESOLVE_ALERT', 'VIEW_FOOTAGE', 'CREATE_NEIGHBOURHOOD', 'JOIN_NEIGHBOURHOOD', 'UPDATE_RETENTION_POLICY', 'REGISTER_ACCOUNT', 'UPDATE_CAMERA_VISIBILITY', 'CONFIGURE_ALERT_THRESHOLD', name='auditaction'), nullable=False),
    sa.Column('target_entity_type', sa.Text(), nullable=True),
    sa.Column('target_entity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text(NOW), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera',
    sa.Column('id', sa.UUID(), server_default=sa.text(GEN_RANDOM_UUID), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'RESTRICTED', 'PRIVATE', name='camera_visibility'), server_default='PRIVATE', nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('rtsp_url', sa.String(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text(NOW), nullable=False),
    sa.ForeignKeyConstraint(['neighbourhood_id'], [NEIGHBOURHOOD_ID], ),
    sa.ForeignKeyConstraint(['property_id'], [PROPERTY_ID], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighbourhood_join_request',
    sa.Column('id', sa.UUID(), server_default=sa.text(GEN_RANDOM_UUID), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text(NOW), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['neighbourhood_id'], [NEIGHBOURHOOD_ID], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], [PROPERTY_ID], ),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ),
    sa.PrimaryKeyConstraint('user_id', 'property_id')
    )
    op.create_table('user_property',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], [PROPERTY_ID], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [USERS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'property_id')
    )
    op.create_table('camera_detection_zone',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text(NOW), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], [CAMERA_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection_event',
    sa.Column('id', sa.UUID(), server_default=sa.text(GEN_RANDOM_UUID), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('frame_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('detection_type', sa.Enum('HUMAN_PRESENCE', 'LOITERING', 'PERIMETER_SCAN', 'WEAPON_DETECTED', 'FALL_DETECTED', name='detection_type'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name='ck_confidence_score_range'),
    sa.ForeignKeyConstraint(['camera_id'], [CAMERA_ID], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retention_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('hot_seconds', sa.Integer(), nullable=False),
    sa.Column('warm_seconds', sa.Integer(), nullable=False),
    sa.Column('cold_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text(NOW), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text(NOW), nullable=False),
    sa.CheckConstraint('camera_id IS NOT NULL OR neighbourhood_id IS NOT NULL', name='check_at_least_one_scope'),
    sa.CheckConstraint('cold_seconds > 0', name='check_cold_seconds_positive'),
    sa.CheckConstraint('hot_seconds > 0', name='check_hot_seconds_positive'),
    sa.CheckConstraint('warm_seconds > 0', name='check_warm_seconds_positive'),
    sa.ForeignKeyConstraint(['camera_id'], [CAMERA_ID], ),
    sa.ForeignKeyConstraint(['neighbourhood_id'], [NEIGHBOURHOOD_ID], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('detection_event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='OPEN', nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text(NOW), nullable=False),
    sa.CheckConstraint("(status = 'RESOLVED' AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL) OR status != 'RESOLVED'", name='check_resolved_fields'),
    sa.ForeignKeyConstraint(['camera_id'], [CAMERA_ID], ),
    sa.ForeignKeyConstraint(['detection_event_id'], ['detection_event.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], [USERS_ID], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('retention_policy')
    op.drop_table('detection_event')
    op.drop_table('camera_detection_zone')
    op.drop_table('user_property')
    op.drop_table('property_user')
    op.drop_table('neighbourhood_join_request')
    op.drop_table('camera')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('property')
    op.drop_index('idx_geospatial_zone_polygon_boundary', table_name='geospatial_zone', postgresql_using='gist')
    op.drop_table('geospatial_zone')
    op.drop_table('neighbourhood')
    # ### end Alembic commands ###
