"""add risk score tables

Revision ID: de4de5897f72
Revises: 2405a75eb269
Create Date: 2026-07-16 07:50:18.339042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4de5897f72'
down_revision: Union[str, Sequence[str], None] = '2405a75eb269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_score_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('classification', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level'), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('alert_count >= 0', name='check_alert_count_non_negative'),
    sa.CheckConstraint('score >= 0.0', name='check_score_non_negative'),
    sa.ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_threshold_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neighbourhood_id', sa.UUID(), nullable=True),
    sa.Column('low_max', sa.Float(), nullable=False),
    sa.Column('medium_max', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('low_max >= 0', name='check_low_max_non_negative'),
    sa.CheckConstraint('medium_max > low_max', name='check_medium_max_greater_than_low_max'),
    sa.CheckConstraint('medium_max >= 0', name='check_medium_max_non_negative'),
    sa.ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_threshold_config')
    op.drop_table('risk_score_history')
    # ### end Alembic commands ###
