"""Changed Audit Log table

Revision ID: e184724b7ff8
Revises: 919661e27f6e
Create Date: 2026-07-04 11:43:31.805416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e184724b7ff8'
down_revision: Union[str, Sequence[str], None] = '919661e27f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_log', sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('audit_log', 'metadata')
    op.add_column('camera', sa.Column('confidence_threshold', sa.Float(), server_default='0.5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'confidence_threshold')
    op.add_column('audit_log', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audit_log', 'new_values')
    op.drop_column('audit_log', 'old_values')
    # ### end Alembic commands ###
