"""add property_id to neighbourhood_join_request

Revision ID: f29ba2d230ef
Revises: 8b72bc8de0d6
Create Date: 2026-08-19 09:46:32.927506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f29ba2d230ef'
down_revision: Union[str, Sequence[str], None] = '8b72bc8de0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neighbourhood_join_request', sa.Column('property_id', sa.UUID(), nullable=False))
    op.create_index('ix_join_request_property_id', 'neighbourhood_join_request', ['property_id'], unique=False)
    op.create_index('uq_join_request_property_neighbourhood_pending', 'neighbourhood_join_request', ['property_id', 'neighbourhood_id', 'status'], unique=False)
    op.create_foreign_key(None, 'neighbourhood_join_request', 'property', ['property_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'neighbourhood_join_request', type_='foreignkey')
    op.drop_index('uq_join_request_property_neighbourhood_pending', table_name='neighbourhood_join_request')
    op.drop_index('ix_join_request_property_id', table_name='neighbourhood_join_request')
    op.drop_column('neighbourhood_join_request', 'property_id')
    # ### end Alembic commands ###
