"""Removed null constraint in Camera model

Revision ID: f4098eeef2e2
Revises: 47ad52d07437
Create Date: 2026-07-26 20:39:39.944755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4098eeef2e2'
down_revision: Union[str, Sequence[str], None] = '47ad52d07437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camera', 'neighbourhood_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('camera', 'neighbourhood_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
