"""add ended_at and tracking_subject_id to incident

Revision ID: f976555ab841
Revises: 2cae7582d70f
Create Date: 2026-09-30 10:54:53.994257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f976555ab841'
down_revision: Union[str, Sequence[str], None] = '2cae7582d70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incident', sa.Column('tracking_subject_id', sa.UUID(), nullable=True))
    op.create_index('ix_incident_active', 'incident', ['ended_at'], unique=False)
    op.create_index('ix_incident_tracking_subject_id', 'incident', ['tracking_subject_id'], unique=False)
    op.create_foreign_key(None, 'incident', 'tracking_subject', ['tracking_subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_index('ix_incident_tracking_subject_id', table_name='incident')
    op.drop_index('ix_incident_active', table_name='incident')
    op.drop_column('incident', 'tracking_subject_id')
    op.drop_column('incident', 'ended_at')
    # ### end Alembic commands ###
