"""Camera table updated

Revision ID: fdcaaba80ba7
Revises: e6ae477c8d7e
Create Date: 2026-07-19 13:42:59.929750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdcaaba80ba7'
down_revision: Union[str, Sequence[str], None] = 'e6ae477c8d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('name', sa.String(), nullable=True))
    op.execute("UPDATE camera SET name = location where name IS NULL")
    op.alter_column('camera', 'name', nullable=False)
    op.add_column('camera', sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'enabled')
    op.drop_column('camera', 'name')
    # ### end Alembic commands ###
