import { useState, useEffect, useRef } from "react";

//globals.css choice explainations
const TOKENS = {
  colors: {
    brand: [
      { name: "Void", hex: "#0A0A0A", rgb: "10, 10, 10", hsl: "0°, 0%, 4%", usage: "Deepest background, modal overlays", token: "--color-void", textColor: "#F5F5F5" },
      { name: "Abyss", hex: "#0D0D0D", rgb: "13, 13, 13", hsl: "0°, 0%, 5%", usage: "Sidebar background, primary canvas", token: "--color-abyss", textColor: "#F5F5F5" },
      { name: "Depth", hex: "#141414", rgb: "20, 20, 20", hsl: "0°, 0%, 8%", usage: "Card backgrounds on dark surfaces", token: "--color-depth", textColor: "#F5F5F5" },
      { name: "Slate", hex: "#1E1E1E", rgb: "30, 30, 30", hsl: "0°, 0%, 12%", usage: "Hover states, secondary containers", token: "--color-slate", textColor: "#F5F5F5" },
      { name: "Gunmetal", hex: "#8A8A8A", rgb: "138, 138, 138", hsl: "0°, 0%, 54%", usage: "Disabled states, borders, dividers", token: "--color-gunmetal", textColor: "#0A0A0A" },
      { name: "Ash", hex: "#A3A3A3", rgb: "163, 163, 163", hsl: "0°, 0%, 64%", usage: "Muted body text, secondary labels", token: "--color-ash", textColor: "#0A0A0A" },
      { name: "Frost", hex: "#F5F5F5", rgb: "245, 245, 245", hsl: "0°, 0%, 96%", usage: "Primary text on dark, high contrast", token: "--color-frost", textColor: "#0A0A0A" },
    ],
    accent: [
      { name: "Emerald", hex: "#10B981", rgb: "16, 185, 129", hsl: "160°, 84%, 39%", usage: "Primary action, brand accent, links, focus rings", token: "--color-green", textColor: "#0A0A0A" },
      { name: "Pulse", hex: "#2D7EFF", rgb: "45, 126, 255", hsl: "218°, 100%, 59%", usage: "Informational alerts, data visualisation secondary", token: "--color-pulse", textColor: "#FFFFFF" },
      { name: "Ice", hex: "#6AB0FF", rgb: "106, 176, 255", hsl: "213°, 100%, 71%", usage: "Hover state of informational, tag highlights", token: "--color-ice", textColor: "#0A0A0A" },
    ],
    semantic: [
      { name: "Threat", hex: "#EF4444", rgb: "239, 68, 68", hsl: "0°, 83%, 60%", usage: "Destructive actions, error states, critical alerts", token: "--color-threat", textColor: "#FFFFFF" },
      { name: "Caution", hex: "#F59E0B", rgb: "245, 158, 11", hsl: "38°, 92%, 50%", usage: "Warnings, medium-risk detections, expiry notices", token: "--color-caution", textColor: "#0A0A0A" },
      { name: "Safe", hex: "#10B981", rgb: "16, 185, 129", hsl: "160°, 84%, 39%", usage: "Success states, confirmed detections, system healthy", token: "--color-safe", textColor: "#0A0A0A" },
      { name: "Info", hex: "#2D7EFF", rgb: "45, 126, 255", hsl: "218°, 100%, 59%", usage: "Informational banners, non-urgent system messages", token: "--color-info", textColor: "#FFFFFF" },
    ],
  },
  contrast: [
    { pair: "Frost on Abyss", fg: "#F5F5F5", bg: "#0D0D0D", ratio: "18.1:1", level: "AAA", usage: "Primary body text" },
    { pair: "Emerald on Abyss", fg: "#10B981", bg: "#0D0D0D", ratio: "7.2:1", level: "AAA", usage: "Brand accent text" },
    { pair: "Ash on Abyss", fg: "#A3A3A3", bg: "#0D0D0D", ratio: "8.9:1", level: "AAA", usage: "Secondary text" },
    { pair: "Frost on Slate", fg: "#F5F5F5", bg: "#1E1E1E", ratio: "14.5:1", level: "AAA", usage: "Card content text" },
    { pair: "Abyss on Emerald", fg: "#0A0A0A", bg: "#10B981", ratio: "7.2:1", level: "AAA", usage: "Primary button label" },
    { pair: "Frost on Depth", fg: "#F5F5F5", bg: "#141414", ratio: "16.8:1", level: "AAA", usage: "Card headings" },
    { pair: "Threat on Abyss", fg: "#EF4444", bg: "#0D0D0D", ratio: "4.7:1", level: "AA", usage: "Error state text" },
    { pair: "Caution on Abyss", fg: "#F59E0B", bg: "#0D0D0D", ratio: "5.8:1", level: "AA", usage: "Warning text" },
  ],
  type: [
    { name: "Display", size: "3rem", lineHeight: "3.5rem", weight: "700", token: "--text-display", sample: "WatchDog", usage: "Hero headlines, splash screens" },
    { name: "H1", size: "2rem", lineHeight: "2.5rem", weight: "700", token: "--text-h1", sample: "Neighbourhood Security", usage: "Page-level headings" },
    { name: "H2", size: "1.5rem", lineHeight: "2rem", weight: "600", token: "--text-h2", sample: "Camera Feeds", usage: "Section headings" },
    { name: "H3", size: "1.25rem", lineHeight: "1.75rem", weight: "600", token: "--text-h3", sample: "Alert summary", usage: "Card headings, subsections" },
    { name: "Body LG", size: "1.125rem", lineHeight: "1.75rem", weight: "400", token: "--text-body-lg", sample: "Monitored zones detected 3 events.", usage: "Lead paragraph text" },
    { name: "Body", size: "1rem", lineHeight: "1.5rem", weight: "400", token: "--text-body", sample: "Camera is active and streaming.", usage: "Standard interface text" },
    { name: "Small", size: "0.875rem", lineHeight: "1.25rem", weight: "400", token: "--text-sm", sample: "Last updated 2 min ago", usage: "Labels, helper text" },
    { name: "Caption", size: "0.75rem", lineHeight: "1rem", weight: "400", token: "--text-caption", sample: "Zone B — Perimeter", usage: "Timestamps, metadata" },
    { name: "Code", size: "0.875rem", lineHeight: "1.25rem", weight: "400", token: "--text-code", sample: "camera.stream.start()", usage: "Code snippets, IDs", mono: true },
  ],
  spacing: [
    { token: "--space-1", value: "4px", usage: "Icon gap, micro nudge" },
    { token: "--space-2", value: "8px", usage: "Inline element gap" },
    { token: "--space-3", value: "12px", usage: "Input padding, compact rows" },
    { token: "--space-4", value: "16px", usage: "Card padding, section gap" },
    { token: "--space-5", value: "24px", usage: "Component margin, between cards" },
    { token: "--space-6", value: "32px", usage: "Section separator" },
    { token: "--space-8", value: "48px", usage: "Page section spacing" },
    { token: "--space-10", value: "64px", usage: "Hero vertical padding" },
    { token: "--space-12", value: "96px", usage: "Full-bleed section height" },
  ],
  radius: [
    { token: "--radius-sm", value: "4px", usage: "Badges, chips, small tags" },
    { token: "--radius-md", value: "8px", usage: "Inputs, buttons, dropdowns" },
    { token: "--radius-lg", value: "12px", usage: "Cards, modals, panels" },
    { token: "--radius-xl", value: "16px", usage: "Sheets, overlays, sidebars" },
    { token: "--radius-full", value: "9999px", usage: "Pills, avatar circles, toggles" },
  ],
  motion: [
    { token: "--motion-instant", value: "0ms", usage: "State changes requiring no animation" },
    { token: "--motion-fast", value: "100ms ease-out", usage: "Hover feedback, button press" },
    { token: "--motion-normal", value: "200ms ease-in-out", usage: "Panel open/close, accordion" },
    { token: "--motion-slow", value: "350ms ease-in-out", usage: "Modal entrance, page transitions" },
    { token: "--motion-alert-pulse", value: "1200ms ease-in-out infinite", usage: "Active threat indicator pulse" },
  ],
  shadows: [
    { token: "--shadow-sm", value: "0 1px 3px rgba(0,0,0,0.3)", usage: "Subtle card lift" },
    { token: "--shadow-md", value: "0 4px 12px rgba(0,0,0,0.4)", usage: "Dropdown menus, tooltips" },
    { token: "--shadow-lg", value: "0 8px 24px rgba(0,0,0,0.5)", usage: "Modals, sheets" },
    { token: "--shadow-alert", value: "0 0 0 3px rgba(239,68,68,0.30)", usage: "Error focus ring" },
  ],
  breakpoints: [
    { name: "Mobile", value: "< 640px", cols: "1", notes: "Single column, stacked nav" },
    { name: "Tablet", value: "640px – 1023px", cols: "2", notes: "Two columns, condensed sidebar" },
    { name: "Desktop", value: "1024px – 1279px", cols: "3", notes: "Full layout with sidebar" },
    { name: "Wide", value: "≥ 1280px", cols: "4", notes: "Extended grid, multi-feed view" },
  ],
};