name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
        run: |
          cat > .env << EOF
          SECRET_KEY=${SECRET_KEY}
          DATABASE_URL=${DATABASE_URL}
          AWS_REGION=${AWS_REGION}
          AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          S3_BUCKET_NAME=${S3_BUCKET_NAME}
          COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
          COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
          COGNITO_REGION=${COGNITO_REGION}
          DETECTION_CONFIDENCE_THRESHOLD=0.6
          EOF
      
      - name: Copy files to EC2
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 #v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".,!frontend"
          target: "/home/ubuntu/app"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 #1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app
            docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
            docker compose exec backend alembic upgrade head